
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 04/02/2011
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="Z00_BURO_CR" , Length = 1020, Length2 = 2040)]
  [Serializable]
  public class Z00_BURO_CR : SAPStructure
  {
   

    /// <summary>
    /// Client
    /// </summary>
 
    [RfcField(AbapName = "MANDT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 0, Offset2 = 0)]
    [XmlElement("MANDT")]
    public string Mandt
    { 
       get
       {
          return _Mandt;
       }
       set
       {
          _Mandt = value;
       }
    }
    private string _Mandt;


    /// <summary>
    /// Contract Number
    /// </summary>
 
    [RfcField(AbapName = "ID_CONSULTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 3, Offset2 = 6)]
    [XmlElement("ID_--5fCONSULTA")]
    public string Id_Consulta
    { 
       get
       {
          return _Id_Consulta;
       }
       set
       {
          _Id_Consulta = value;
       }
    }
    private string _Id_Consulta;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "LONGITUD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 16, Offset2 = 32)]
    [XmlElement("LONGITUD")]
    public string Longitud
    { 
       get
       {
          return _Longitud;
       }
       set
       {
          _Longitud = value;
       }
    }
    private string _Longitud;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "DECLARACION1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 250, Length2 = 500, Offset = 20, Offset2 = 40)]
    [XmlElement("DECLARACION1")]
    public string Declaracion1
    { 
       get
       {
          return _Declaracion1;
       }
       set
       {
          _Declaracion1 = value;
       }
    }
    private string _Declaracion1;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "DECLARACION2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 250, Length2 = 500, Offset = 270, Offset2 = 540)]
    [XmlElement("DECLARACION2")]
    public string Declaracion2
    { 
       get
       {
          return _Declaracion2;
       }
       set
       {
          _Declaracion2 = value;
       }
    }
    private string _Declaracion2;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "DECLARACION3", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 250, Length2 = 500, Offset = 520, Offset2 = 1040)]
    [XmlElement("DECLARACION3")]
    public string Declaracion3
    { 
       get
       {
          return _Declaracion3;
       }
       set
       {
          _Declaracion3 = value;
       }
    }
    private string _Declaracion3;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "DECLARACION4", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 250, Length2 = 500, Offset = 770, Offset2 = 1540)]
    [XmlElement("DECLARACION4")]
    public string Declaracion4
    { 
       get
       {
          return _Declaracion4;
       }
       set
       {
          _Declaracion4 = value;
       }
    }
    private string _Declaracion4;

  }

}
