
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 04/02/2011
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="Z00_BURO_ES" , Length = 44, Length2 = 88)]
  [Serializable]
  public class Z00_BURO_ES : SAPStructure
  {
   

    /// <summary>
    /// Client
    /// </summary>
 
    [RfcField(AbapName = "MANDT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 0, Offset2 = 0)]
    [XmlElement("MANDT")]
    public string Mandt
    { 
       get
       {
          return _Mandt;
       }
       set
       {
          _Mandt = value;
       }
    }
    private string _Mandt;


    /// <summary>
    /// Contract Number
    /// </summary>
 
    [RfcField(AbapName = "ID_CONSULTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 3, Offset2 = 6)]
    [XmlElement("ID_--5fCONSULTA")]
    public string Id_Consulta
    { 
       get
       {
          return _Id_Consulta;
       }
       set
       {
          _Id_Consulta = value;
       }
    }
    private string _Id_Consulta;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "LONGITUD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 9, Length2 = 18, Offset = 16, Offset2 = 32)]
    [XmlElement("LONGITUD")]
    public string Longitud
    { 
       get
       {
          return _Longitud;
       }
       set
       {
          _Longitud = value;
       }
    }
    private string _Longitud;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CONTROL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 25, Offset2 = 50)]
    [XmlElement("CONTROL")]
    public string Control
    { 
       get
       {
          return _Control;
       }
       set
       {
          _Control = value;
       }
    }
    private string _Control;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FIN_CHAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 38, Offset2 = 76)]
    [XmlElement("FIN_--5fCHAR")]
    public string Fin_Char
    { 
       get
       {
          return _Fin_Char;
       }
       set
       {
          _Fin_Char = value;
       }
    }
    private string _Fin_Char;

  }

}
