
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 16/12/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{

  /// <summary>
  /// Client SAP proxy class
  /// </summary>
  [WebServiceBinding(Name="dummy.Binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
  [Serializable]
  public class SapConnectorClientToBC : SAPClient
  {
    /// <summary>
    /// Initializes a new SapConnectorClientToBC.
    /// </summary>
    public SapConnectorClientToBC(){}

    /// <summary>
    /// Initializes a new SapConnectorClientToBC with a new connection based on the specified connection string.
    /// </summary>
    /// <param name="connectionString">A connection string (e.g. RFC or URL) specifying the system where the proxy should connect to.</param>
    public SapConnectorClientToBC(string connectionString) : base(connectionString){}

    /// <summary>
    /// Initializes a new SapConnectorClientToBC instance and adds it to the given container.
    /// This allows automated connection mananged by VS component designer:
    /// If container is disposed, it will also dispose this SAPClient instance,
    /// which will dispose a contained connection if needed.
    /// </summary>
    /// <param name="container"<The container where the new SAPClient instance is to be added.>/param<
    public SapConnectorClientToBC(System.ComponentModel.IContainer container) : base(container) {}    
  
    /// <summary>
    /// Exception constant for ABAP-Exception ID_NOT_FOUND
    /// </summary>
    public const string Id_Not_Found = "ID_NOT_FOUND";
   
    /// <summary>
    /// Exception constant for ABAP-Exception ID_OVERWRITE_ERROR
    /// </summary>
    public const string Id_Overwrite_Error = "ID_OVERWRITE_ERROR";
   
    /// <summary>
    /// Remote Function Module ZRFC_BURO_RESPUESTA.  
    /// 
    /// </summary>
    /// <param name="Error_Code"></param>
    /// <param name="Id_Consulta"></param>
    /// <param name="Partner"></param>
    /// <param name="Ar"></param>
    /// <param name="Cr"></param>
    /// <param name="Hi"></param>
    /// <param name="Hr"></param>
    /// <param name="Intl"></param>
    /// <param name="Iq"></param>
    /// <param name="Pa"></param>
    /// <param name="Pe"></param>
    /// <param name="Pn"></param>
    /// <param name="Rs"></param>
    /// <param name="Sc"></param>
    /// <param name="Tl"></param>
    /// <param name="Ur"></param> 
    /// <exception cref="Id_Not_Found"/> 
    /// <exception cref="Id_Overwrite_Error"/>
    [RfcMethod(AbapName = "ZRFC_BURO_RESPUESTA")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZRFC_BURO_RESPUESTA",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZRFC_BURO_RESPUESTA",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZRFC_BURO_RESPUESTA.Response")]
    public virtual void Zrfc_Buro_Respuesta (

     [RfcParameter(AbapName = "ERROR_CODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 2, Length2 = 4)]
     [XmlElement("ERROR_--5fCODE", IsNullable=false, Namespace="")]
     string Error_Code,
     [RfcParameter(AbapName = "ID_CONSULTA",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 13, Length2 = 26)]
     [XmlElement("ID_--5fCONSULTA", IsNullable=false, Namespace="")]
     string Id_Consulta,
     [RfcParameter(AbapName = "PARTNER",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("PARTNER", IsNullable=false, Namespace="")]
     string Partner,
     [RfcParameter(AbapName = "AR",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("AR", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_ARTable Ar,
     [RfcParameter(AbapName = "CR",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("CR", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_CRTable Cr,
     [RfcParameter(AbapName = "HI",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("HI", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_HITable Hi,
     [RfcParameter(AbapName = "HR",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("HR", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_HRTable Hr,
     [RfcParameter(AbapName = "INTL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("INTL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_INTLTable Intl,
     [RfcParameter(AbapName = "IQ",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("IQ", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_IQTable Iq,
     [RfcParameter(AbapName = "PA",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("PA", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_PATable Pa,
     [RfcParameter(AbapName = "PE",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("PE", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_PETable Pe,
     [RfcParameter(AbapName = "PN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("PN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_PNTable Pn,
     [RfcParameter(AbapName = "RS",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("RS", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_RSTable Rs,
     [RfcParameter(AbapName = "SC",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("SC", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_SCTable Sc,
     [RfcParameter(AbapName = "TL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("TL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_TLTable Tl,
     [RfcParameter(AbapName = "UR",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("UR", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_URTable Ur)
    {
        object[]results = null;
        results = this.SAPInvoke("Zrfc_Buro_Respuesta",new object[] {
                            Error_Code,Id_Consulta,Partner,Ar,Cr,Hi,Hr,Intl,Iq,Pa,Pe,Pn,Rs,Sc,Tl,Ur });
        Ar = (Z00_BURO_ARTable) results[0];
        Cr = (Z00_BURO_CRTable) results[1];
        Hi = (Z00_BURO_HITable) results[2];
        Hr = (Z00_BURO_HRTable) results[3];
        Intl = (Z00_BURO_INTLTable) results[4];
        Iq = (Z00_BURO_IQTable) results[5];
        Pa = (Z00_BURO_PATable) results[6];
        Pe = (Z00_BURO_PETable) results[7];
        Pn = (Z00_BURO_PNTable) results[8];
        Rs = (Z00_BURO_RSTable) results[9];
        Sc = (Z00_BURO_SCTable) results[10];
        Tl = (Z00_BURO_TLTable) results[11];
        Ur = (Z00_BURO_URTable) results[12];

    }

    /// <summary>
    /// Remote Function Module ZRFC_BURO_BP.  
    /// 
    /// </summary>
    /// <param name="Id_Consulta"></param>
    /// <param name="Partner"></param>
    /// <param name="Intl"></param>
    /// <param name="Pa"></param>
    /// <param name="Pn"></param>
    [RfcMethod(AbapName = "ZRFC_BURO_BP")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZRFC_BURO_BP",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZRFC_BURO_BP",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZRFC_BURO_BP.Response")]
    public virtual void Zrfc_Buro_Bp (

     [RfcParameter(AbapName = "ID_CONSULTA",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 13, Length2 = 26)]
     [XmlElement("ID_--5fCONSULTA", IsNullable=false, Namespace="")]
     string Id_Consulta,
     [RfcParameter(AbapName = "PARTNER",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("PARTNER", IsNullable=false, Namespace="")]
     string Partner,
     [RfcParameter(AbapName = "INTL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("INTL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_INTLTable Intl,
     [RfcParameter(AbapName = "PA",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("PA", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_PATable Pa,
     [RfcParameter(AbapName = "PN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = true, Direction = RFCINOUT.INOUT)]
     [XmlArray("PN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref Z00_BURO_PNTable Pn)
    {
        object[]results = null;
        results = this.SAPInvoke("Zrfc_Buro_Bp",new object[] {
                            Id_Consulta,Partner,Intl,Pa,Pn });
        Intl = (Z00_BURO_INTLTable) results[0];
        Pa = (Z00_BURO_PATable) results[1];
        Pn = (Z00_BURO_PNTable) results[2];

    }

  } 

}
