
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 16/12/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="Z00_BURO_IQ" , Length = 133, Length2 = 266)]
  [Serializable]
  public class Z00_BURO_IQ : SAPStructure
  {
   

    /// <summary>
    /// Client
    /// </summary>
 
    [RfcField(AbapName = "MANDT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 0, Offset2 = 0)]
    [XmlElement("MANDT")]
    public string Mandt
    { 
       get
       {
          return _Mandt;
       }
       set
       {
          _Mandt = value;
       }
    }
    private string _Mandt;


    /// <summary>
    /// Contract Number
    /// </summary>
 
    [RfcField(AbapName = "ID_CONSULTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 3, Offset2 = 6)]
    [XmlElement("ID_--5fCONSULTA")]
    public string Id_Consulta
    { 
       get
       {
          return _Id_Consulta;
       }
       set
       {
          _Id_Consulta = value;
       }
    }
    private string _Id_Consulta;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CONSECUTIVO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 16, Offset2 = 32)]
    [XmlElement("CONSECUTIVO")]
    public string Consecutivo
    { 
       get
       {
          return _Consecutivo;
       }
       set
       {
          _Consecutivo = value;
       }
    }
    private string _Consecutivo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FECHA_CONSULTA", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 19, Offset2 = 38)]
    [XmlElement("FECHA_--5fCONSULTA")]
    public string Fecha_Consulta
    { 
       get
       {
          return _Fecha_Consulta;
       }
       set
       {
          _Fecha_Consulta = value;
       }
    }
    private string _Fecha_Consulta;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "ID_BURO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Length2 = 8, Offset = 27, Offset2 = 54)]
    [XmlElement("ID_--5fBURO")]
    public string Id_Buro
    { 
       get
       {
          return _Id_Buro;
       }
       set
       {
          _Id_Buro = value;
       }
    }
    private string _Id_Buro;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "OTORGANTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 31, Offset2 = 62)]
    [XmlElement("OTORGANTE")]
    public string Otorgante
    { 
       get
       {
          return _Otorgante;
       }
       set
       {
          _Otorgante = value;
       }
    }
    private string _Otorgante;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "NOMBRE_OTORGANTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Length2 = 32, Offset = 41, Offset2 = 82)]
    [XmlElement("NOMBRE_--5fOTORGANTE")]
    public string Nombre_Otorgante
    { 
       get
       {
          return _Nombre_Otorgante;
       }
       set
       {
          _Nombre_Otorgante = value;
       }
    }
    private string _Nombre_Otorgante;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "TELEFONO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 11, Length2 = 22, Offset = 57, Offset2 = 114)]
    [XmlElement("TELEFONO")]
    public string Telefono
    { 
       get
       {
          return _Telefono;
       }
       set
       {
          _Telefono = value;
       }
    }
    private string _Telefono;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "TIPO_CONTRATO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 68, Offset2 = 136)]
    [XmlElement("TIPO_--5fCONTRATO")]
    public string Tipo_Contrato
    { 
       get
       {
          return _Tipo_Contrato;
       }
       set
       {
          _Tipo_Contrato = value;
       }
    }
    private string _Tipo_Contrato;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "MONEDA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 70, Offset2 = 140)]
    [XmlElement("MONEDA")]
    public string Moneda
    { 
       get
       {
          return _Moneda;
       }
       set
       {
          _Moneda = value;
       }
    }
    private string _Moneda;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "IMPORTE", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 9, Length2 = 18, Offset = 72, Offset2 = 144)]
    [XmlElement("IMPORTE")]
    public string Importe
    { 
       get
       {
          return _Importe;
       }
       set
       {
          _Importe = value;
       }
    }
    private string _Importe;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "TIPO_RESPON", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 81, Offset2 = 162)]
    [XmlElement("TIPO_--5fRESPON")]
    public string Tipo_Respon
    { 
       get
       {
          return _Tipo_Respon;
       }
       set
       {
          _Tipo_Respon = value;
       }
    }
    private string _Tipo_Respon;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CONSUMIDOR_NUEVO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 82, Offset2 = 164)]
    [XmlElement("CONSUMIDOR_--5fNUEVO")]
    public string Consumidor_Nuevo
    { 
       get
       {
          return _Consumidor_Nuevo;
       }
       set
       {
          _Consumidor_Nuevo = value;
       }
    }
    private string _Consumidor_Nuevo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "RESULTADO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 25, Length2 = 50, Offset = 83, Offset2 = 166)]
    [XmlElement("RESULTADO")]
    public string Resultado
    { 
       get
       {
          return _Resultado;
       }
       set
       {
          _Resultado = value;
       }
    }
    private string _Resultado;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "SIC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 25, Length2 = 50, Offset = 108, Offset2 = 216)]
    [XmlElement("SIC")]
    public string Sic
    { 
       get
       {
          return _Sic;
       }
       set
       {
          _Sic = value;
       }
    }
    private string _Sic;

  }

}
