
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 16/12/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="Z00_BURO_SC" , Length = 67, Length2 = 134)]
  [Serializable]
  public class Z00_BURO_SC : SAPStructure
  {
   

    /// <summary>
    /// Client
    /// </summary>
 
    [RfcField(AbapName = "MANDT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 0, Offset2 = 0)]
    [XmlElement("MANDT")]
    public string Mandt
    { 
       get
       {
          return _Mandt;
       }
       set
       {
          _Mandt = value;
       }
    }
    private string _Mandt;


    /// <summary>
    /// Contract Number
    /// </summary>
 
    [RfcField(AbapName = "ID_CONSULTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 3, Offset2 = 6)]
    [XmlElement("ID_--5fCONSULTA")]
    public string Id_Consulta
    { 
       get
       {
          return _Id_Consulta;
       }
       set
       {
          _Id_Consulta = value;
       }
    }
    private string _Id_Consulta;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CONSECUTIVO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 16, Offset2 = 32)]
    [XmlElement("CONSECUTIVO")]
    public string Consecutivo
    { 
       get
       {
          return _Consecutivo;
       }
       set
       {
          _Consecutivo = value;
       }
    }
    private string _Consecutivo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "NOMBRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 19, Offset2 = 38)]
    [XmlElement("NOMBRE")]
    public string Nombre
    { 
       get
       {
          return _Nombre;
       }
       set
       {
          _Nombre = value;
       }
    }
    private string _Nombre;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CODIGO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 49, Offset2 = 98)]
    [XmlElement("CODIGO")]
    public string Codigo
    { 
       get
       {
          return _Codigo;
       }
       set
       {
          _Codigo = value;
       }
    }
    private string _Codigo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "VALOR", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Length2 = 8, Offset = 52, Offset2 = 104)]
    [XmlElement("VALOR")]
    public string Valor
    { 
       get
       {
          return _Valor;
       }
       set
       {
          _Valor = value;
       }
    }
    private string _Valor;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "RAZON1", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 56, Offset2 = 112)]
    [XmlElement("RAZON1")]
    public string Razon1
    { 
       get
       {
          return _Razon1;
       }
       set
       {
          _Razon1 = value;
       }
    }
    private string _Razon1;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "RAZON2", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 59, Offset2 = 118)]
    [XmlElement("RAZON2")]
    public string Razon2
    { 
       get
       {
          return _Razon2;
       }
       set
       {
          _Razon2 = value;
       }
    }
    private string _Razon2;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "RAZON3", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 62, Offset2 = 124)]
    [XmlElement("RAZON3")]
    public string Razon3
    { 
       get
       {
          return _Razon3;
       }
       set
       {
          _Razon3 = value;
       }
    }
    private string _Razon3;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "ERROR", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Length2 = 4, Offset = 65, Offset2 = 130)]
    [XmlElement("ERROR")]
    public string Error
    { 
       get
       {
          return _Error;
       }
       set
       {
          _Error = value;
       }
    }
    private string _Error;

  }

}
