
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 16/12/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="Z00_BURO_UR" , Length = 239, Length2 = 478)]
  [Serializable]
  public class Z00_BURO_UR : SAPStructure
  {
   

    /// <summary>
    /// Client
    /// </summary>
 
    [RfcField(AbapName = "MANDT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 0, Offset2 = 0)]
    [XmlElement("MANDT")]
    public string Mandt
    { 
       get
       {
          return _Mandt;
       }
       set
       {
          _Mandt = value;
       }
    }
    private string _Mandt;


    /// <summary>
    /// Contract Number
    /// </summary>
 
    [RfcField(AbapName = "ID_CONSULTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 3, Offset2 = 6)]
    [XmlElement("ID_--5fCONSULTA")]
    public string Id_Consulta
    { 
       get
       {
          return _Id_Consulta;
       }
       set
       {
          _Id_Consulta = value;
       }
    }
    private string _Id_Consulta;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "REF_OPERADOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 25, Length2 = 50, Offset = 16, Offset2 = 32)]
    [XmlElement("REF_--5fOPERADOR")]
    public string Ref_Operador
    { 
       get
       {
          return _Ref_Operador;
       }
       set
       {
          _Ref_Operador = value;
       }
    }
    private string _Ref_Operador;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "SOLICITUD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 41, Offset2 = 82)]
    [XmlElement("SOLICITUD")]
    public string Solicitud
    { 
       get
       {
          return _Solicitud;
       }
       set
       {
          _Solicitud = value;
       }
    }
    private string _Solicitud;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "VERSION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 45, Offset2 = 90)]
    [XmlElement("VERSION")]
    public string Version
    { 
       get
       {
          return _Version;
       }
       set
       {
          _Version = value;
       }
    }
    private string _Version;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "PRODUCTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 47, Offset2 = 94)]
    [XmlElement("PRODUCTO")]
    public string Producto
    { 
       get
       {
          return _Producto;
       }
       set
       {
          _Producto = value;
       }
    }
    private string _Producto;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "PASSWORD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 14, Length2 = 28, Offset = 50, Offset2 = 100)]
    [XmlElement("PASSWORD")]
    public string Password
    { 
       get
       {
          return _Password;
       }
       set
       {
          _Password = value;
       }
    }
    private string _Password;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "SEGMENTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 64, Offset2 = 128)]
    [XmlElement("SEGMENTO")]
    public string Segmento
    { 
       get
       {
          return _Segmento;
       }
       set
       {
          _Segmento = value;
       }
    }
    private string _Segmento;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "ULT_INFO_VALIDA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Length2 = 12, Offset = 66, Offset2 = 132)]
    [XmlElement("ULT_--5fINFO_--5fVALIDA")]
    public string Ult_Info_Valida
    { 
       get
       {
          return _Ult_Info_Valida;
       }
       set
       {
          _Ult_Info_Valida = value;
       }
    }
    private string _Ult_Info_Valida;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "INFO_ERR_CONSUL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 46, Length2 = 92, Offset = 72, Offset2 = 144)]
    [XmlElement("INFO_--5fERR_--5fCONSUL")]
    public string Info_Err_Consul
    { 
       get
       {
          return _Info_Err_Consul;
       }
       set
       {
          _Info_Err_Consul = value;
       }
    }
    private string _Info_Err_Consul;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "VALOR_ERR_REL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 92, Length2 = 184, Offset = 118, Offset2 = 236)]
    [XmlElement("VALOR_--5fERR_--5fREL")]
    public string Valor_Err_Rel
    { 
       get
       {
          return _Valor_Err_Rel;
       }
       set
       {
          _Valor_Err_Rel = value;
       }
    }
    private string _Valor_Err_Rel;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "ERROR_BURO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 210, Offset2 = 420)]
    [XmlElement("ERROR_--5fBURO")]
    public string Error_Buro
    { 
       get
       {
          return _Error_Buro;
       }
       set
       {
          _Error_Buro = value;
       }
    }
    private string _Error_Buro;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "ETIQUETA_SEG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 211, Offset2 = 422)]
    [XmlElement("ETIQUETA_--5fSEG")]
    public string Etiqueta_Seg
    { 
       get
       {
          return _Etiqueta_Seg;
       }
       set
       {
          _Etiqueta_Seg = value;
       }
    }
    private string _Etiqueta_Seg;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "ORDEN_ERR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 213, Offset2 = 426)]
    [XmlElement("ORDEN_--5fERR")]
    public string Orden_Err
    { 
       get
       {
          return _Orden_Err;
       }
       set
       {
          _Orden_Err = value;
       }
    }
    private string _Orden_Err;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "NUM_ERR_SEG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 217, Offset2 = 434)]
    [XmlElement("NUM_--5fERR_--5fSEG")]
    public string Num_Err_Seg
    { 
       get
       {
          return _Num_Err_Seg;
       }
       set
       {
          _Num_Err_Seg = value;
       }
    }
    private string _Num_Err_Seg;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "REQUERIDO1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 219, Offset2 = 438)]
    [XmlElement("REQUERIDO1")]
    public string Requerido1
    { 
       get
       {
          return _Requerido1;
       }
       set
       {
          _Requerido1 = value;
       }
    }
    private string _Requerido1;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "REQUERIDO2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 223, Offset2 = 446)]
    [XmlElement("REQUERIDO2")]
    public string Requerido2
    { 
       get
       {
          return _Requerido2;
       }
       set
       {
          _Requerido2 = value;
       }
    }
    private string _Requerido2;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "REQUERIDO3", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 227, Offset2 = 454)]
    [XmlElement("REQUERIDO3")]
    public string Requerido3
    { 
       get
       {
          return _Requerido3;
       }
       set
       {
          _Requerido3 = value;
       }
    }
    private string _Requerido3;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "REQUERIDO4", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 231, Offset2 = 462)]
    [XmlElement("REQUERIDO4")]
    public string Requerido4
    { 
       get
       {
          return _Requerido4;
       }
       set
       {
          _Requerido4 = value;
       }
    }
    private string _Requerido4;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "REQUERIDO5", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 235, Offset2 = 470)]
    [XmlElement("REQUERIDO5")]
    public string Requerido5
    { 
       get
       {
          return _Requerido5;
       }
       set
       {
          _Requerido5 = value;
       }
    }
    private string _Requerido5;

  }

}
