
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 16/12/2010
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="Z00_BURO_PE" , Length = 388, Length2 = 776)]
  [Serializable]
  public class Z00_BURO_PE : SAPStructure
  {
   

    /// <summary>
    /// Client
    /// </summary>
 
    [RfcField(AbapName = "MANDT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 0, Offset2 = 0)]
    [XmlElement("MANDT")]
    public string Mandt
    { 
       get
       {
          return _Mandt;
       }
       set
       {
          _Mandt = value;
       }
    }
    private string _Mandt;


    /// <summary>
    /// Contract Number
    /// </summary>
 
    [RfcField(AbapName = "ID_CONSULTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 3, Offset2 = 6)]
    [XmlElement("ID_--5fCONSULTA")]
    public string Id_Consulta
    { 
       get
       {
          return _Id_Consulta;
       }
       set
       {
          _Id_Consulta = value;
       }
    }
    private string _Id_Consulta;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CONSECUTIVO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Length2 = 6, Offset = 16, Offset2 = 32)]
    [XmlElement("CONSECUTIVO")]
    public string Consecutivo
    { 
       get
       {
          return _Consecutivo;
       }
       set
       {
          _Consecutivo = value;
       }
    }
    private string _Consecutivo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "RAZONSOCIAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 19, Offset2 = 38)]
    [XmlElement("RAZONSOCIAL")]
    public string Razonsocial
    { 
       get
       {
          return _Razonsocial;
       }
       set
       {
          _Razonsocial = value;
       }
    }
    private string _Razonsocial;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "DIRECCION1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 59, Offset2 = 118)]
    [XmlElement("DIRECCION1")]
    public string Direccion1
    { 
       get
       {
          return _Direccion1;
       }
       set
       {
          _Direccion1 = value;
       }
    }
    private string _Direccion1;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "DIRECCION2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 99, Offset2 = 198)]
    [XmlElement("DIRECCION2")]
    public string Direccion2
    { 
       get
       {
          return _Direccion2;
       }
       set
       {
          _Direccion2 = value;
       }
    }
    private string _Direccion2;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "COLONIA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 139, Offset2 = 278)]
    [XmlElement("COLONIA")]
    public string Colonia
    { 
       get
       {
          return _Colonia;
       }
       set
       {
          _Colonia = value;
       }
    }
    private string _Colonia;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "MUNICIPIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 179, Offset2 = 358)]
    [XmlElement("MUNICIPIO")]
    public string Municipio
    { 
       get
       {
          return _Municipio;
       }
       set
       {
          _Municipio = value;
       }
    }
    private string _Municipio;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CIUDAD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 219, Offset2 = 438)]
    [XmlElement("CIUDAD")]
    public string Ciudad
    { 
       get
       {
          return _Ciudad;
       }
       set
       {
          _Ciudad = value;
       }
    }
    private string _Ciudad;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "ESTADO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 259, Offset2 = 518)]
    [XmlElement("ESTADO")]
    public string Estado
    { 
       get
       {
          return _Estado;
       }
       set
       {
          _Estado = value;
       }
    }
    private string _Estado;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CP", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 5, Length2 = 10, Offset = 263, Offset2 = 526)]
    [XmlElement("CP")]
    public string Cp
    { 
       get
       {
          return _Cp;
       }
       set
       {
          _Cp = value;
       }
    }
    private string _Cp;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "TELEFONO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 11, Length2 = 22, Offset = 268, Offset2 = 536)]
    [XmlElement("TELEFONO")]
    public string Telefono
    { 
       get
       {
          return _Telefono;
       }
       set
       {
          _Telefono = value;
       }
    }
    private string _Telefono;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "EXTENSION_TEL", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 8, Length2 = 16, Offset = 279, Offset2 = 558)]
    [XmlElement("EXTENSION_--5fTEL")]
    public string Extension_Tel
    { 
       get
       {
          return _Extension_Tel;
       }
       set
       {
          _Extension_Tel = value;
       }
    }
    private string _Extension_Tel;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FAX", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 11, Length2 = 22, Offset = 287, Offset2 = 574)]
    [XmlElement("FAX")]
    public string Fax
    { 
       get
       {
          return _Fax;
       }
       set
       {
          _Fax = value;
       }
    }
    private string _Fax;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CARGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 298, Offset2 = 596)]
    [XmlElement("CARGO")]
    public string Cargo
    { 
       get
       {
          return _Cargo;
       }
       set
       {
          _Cargo = value;
       }
    }
    private string _Cargo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FECHA_CONTRATA", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 328, Offset2 = 656)]
    [XmlElement("FECHA_--5fCONTRATA")]
    public string Fecha_Contrata
    { 
       get
       {
          return _Fecha_Contrata;
       }
       set
       {
          _Fecha_Contrata = value;
       }
    }
    private string _Fecha_Contrata;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "MONEDA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 336, Offset2 = 672)]
    [XmlElement("MONEDA")]
    public string Moneda
    { 
       get
       {
          return _Moneda;
       }
       set
       {
          _Moneda = value;
       }
    }
    private string _Moneda;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "SALARIO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 9, Length2 = 18, Offset = 338, Offset2 = 676)]
    [XmlElement("SALARIO")]
    public string Salario
    { 
       get
       {
          return _Salario;
       }
       set
       {
          _Salario = value;
       }
    }
    private string _Salario;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "BASE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 347, Offset2 = 694)]
    [XmlElement("BASE")]
    public string Base
    { 
       get
       {
          return _Base;
       }
       set
       {
          _Base = value;
       }
    }
    private string _Base;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "NUM_EMPLEADO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 348, Offset2 = 696)]
    [XmlElement("NUM_--5fEMPLEADO")]
    public string Num_Empleado
    { 
       get
       {
          return _Num_Empleado;
       }
       set
       {
          _Num_Empleado = value;
       }
    }
    private string _Num_Empleado;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FECHA_ULT_DIA", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 363, Offset2 = 726)]
    [XmlElement("FECHA_--5fULT_--5fDIA")]
    public string Fecha_Ult_Dia
    { 
       get
       {
          return _Fecha_Ult_Dia;
       }
       set
       {
          _Fecha_Ult_Dia = value;
       }
    }
    private string _Fecha_Ult_Dia;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FECHA_REGISTRO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 371, Offset2 = 742)]
    [XmlElement("FECHA_--5fREGISTRO")]
    public string Fecha_Registro
    { 
       get
       {
          return _Fecha_Registro;
       }
       set
       {
          _Fecha_Registro = value;
       }
    }
    private string _Fecha_Registro;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FECHA_VERIF", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 379, Offset2 = 758)]
    [XmlElement("FECHA_--5fVERIF")]
    public string Fecha_Verif
    { 
       get
       {
          return _Fecha_Verif;
       }
       set
       {
          _Fecha_Verif = value;
       }
    }
    private string _Fecha_Verif;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "MODO_VERIF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 387, Offset2 = 774)]
    [XmlElement("MODO_--5fVERIF")]
    public string Modo_Verif
    { 
       get
       {
          return _Modo_Verif;
       }
       set
       {
          _Modo_Verif = value;
       }
    }
    private string _Modo_Verif;

  }

}
