
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 04/02/2011
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="Z00_BURO_PN" , Length = 310, Length2 = 620)]
  [Serializable]
  public class Z00_BURO_PN : SAPStructure
  {
   

    /// <summary>
    /// Client
    /// </summary>
 
    [RfcField(AbapName = "MANDT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 0, Offset2 = 0)]
    [XmlElement("MANDT")]
    public string Mandt
    { 
       get
       {
          return _Mandt;
       }
       set
       {
          _Mandt = value;
       }
    }
    private string _Mandt;


    /// <summary>
    /// Contract Number
    /// </summary>
 
    [RfcField(AbapName = "ID_CONSULTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 3, Offset2 = 6)]
    [XmlElement("ID_--5fCONSULTA")]
    public string Id_Consulta
    { 
       get
       {
          return _Id_Consulta;
       }
       set
       {
          _Id_Consulta = value;
       }
    }
    private string _Id_Consulta;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "APE_PATERNO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 26, Length2 = 52, Offset = 16, Offset2 = 32)]
    [XmlElement("APE_--5fPATERNO")]
    public string Ape_Paterno
    { 
       get
       {
          return _Ape_Paterno;
       }
       set
       {
          _Ape_Paterno = value;
       }
    }
    private string _Ape_Paterno;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "APE_MATERNO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 26, Length2 = 52, Offset = 42, Offset2 = 84)]
    [XmlElement("APE_--5fMATERNO")]
    public string Ape_Materno
    { 
       get
       {
          return _Ape_Materno;
       }
       set
       {
          _Ape_Materno = value;
       }
    }
    private string _Ape_Materno;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "APE_ADICIONAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 26, Length2 = 52, Offset = 68, Offset2 = 136)]
    [XmlElement("APE_--5fADICIONAL")]
    public string Ape_Adicional
    { 
       get
       {
          return _Ape_Adicional;
       }
       set
       {
          _Ape_Adicional = value;
       }
    }
    private string _Ape_Adicional;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "PRIMER_NOMBRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 26, Length2 = 52, Offset = 94, Offset2 = 188)]
    [XmlElement("PRIMER_--5fNOMBRE")]
    public string Primer_Nombre
    { 
       get
       {
          return _Primer_Nombre;
       }
       set
       {
          _Primer_Nombre = value;
       }
    }
    private string _Primer_Nombre;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "SEGUNDO_NOMBRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 26, Length2 = 52, Offset = 120, Offset2 = 240)]
    [XmlElement("SEGUNDO_--5fNOMBRE")]
    public string Segundo_Nombre
    { 
       get
       {
          return _Segundo_Nombre;
       }
       set
       {
          _Segundo_Nombre = value;
       }
    }
    private string _Segundo_Nombre;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FECHA_NACIMIENTO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 146, Offset2 = 292)]
    [XmlElement("FECHA_--5fNACIMIENTO")]
    public string Fecha_Nacimiento
    { 
       get
       {
          return _Fecha_Nacimiento;
       }
       set
       {
          _Fecha_Nacimiento = value;
       }
    }
    private string _Fecha_Nacimiento;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "RFC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 13, Length2 = 26, Offset = 154, Offset2 = 308)]
    [XmlElement("RFC")]
    public string Rfc
    { 
       get
       {
          return _Rfc;
       }
       set
       {
          _Rfc = value;
       }
    }
    private string _Rfc;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "PREFIJO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 167, Offset2 = 334)]
    [XmlElement("PREFIJO")]
    public string Prefijo
    { 
       get
       {
          return _Prefijo;
       }
       set
       {
          _Prefijo = value;
       }
    }
    private string _Prefijo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "SUFIJO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 171, Offset2 = 342)]
    [XmlElement("SUFIJO")]
    public string Sufijo
    { 
       get
       {
          return _Sufijo;
       }
       set
       {
          _Sufijo = value;
       }
    }
    private string _Sufijo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "NACIONALIDAD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 175, Offset2 = 350)]
    [XmlElement("NACIONALIDAD")]
    public string Nacionalidad
    { 
       get
       {
          return _Nacionalidad;
       }
       set
       {
          _Nacionalidad = value;
       }
    }
    private string _Nacionalidad;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "RESIDENCIA", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 1, Length2 = 2, Offset = 177, Offset2 = 354)]
    [XmlElement("RESIDENCIA")]
    public string Residencia
    { 
       get
       {
          return _Residencia;
       }
       set
       {
          _Residencia = value;
       }
    }
    private string _Residencia;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "LIC_CONDUCIR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 178, Offset2 = 356)]
    [XmlElement("LIC_--5fCONDUCIR")]
    public string Lic_Conducir
    { 
       get
       {
          return _Lic_Conducir;
       }
       set
       {
          _Lic_Conducir = value;
       }
    }
    private string _Lic_Conducir;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "EDO_CIVIL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 198, Offset2 = 396)]
    [XmlElement("EDO_--5fCIVIL")]
    public string Edo_Civil
    { 
       get
       {
          return _Edo_Civil;
       }
       set
       {
          _Edo_Civil = value;
       }
    }
    private string _Edo_Civil;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "SEXO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 199, Offset2 = 398)]
    [XmlElement("SEXO")]
    public string Sexo
    { 
       get
       {
          return _Sexo;
       }
       set
       {
          _Sexo = value;
       }
    }
    private string _Sexo;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "CEDULA_PROF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 200, Offset2 = 400)]
    [XmlElement("CEDULA_--5fPROF")]
    public string Cedula_Prof
    { 
       get
       {
          return _Cedula_Prof;
       }
       set
       {
          _Cedula_Prof = value;
       }
    }
    private string _Cedula_Prof;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "REG_ELECTORAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 220, Offset2 = 440)]
    [XmlElement("REG_--5fELECTORAL")]
    public string Reg_Electoral
    { 
       get
       {
          return _Reg_Electoral;
       }
       set
       {
          _Reg_Electoral = value;
       }
    }
    private string _Reg_Electoral;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "IMPUESTOS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Length2 = 40, Offset = 240, Offset2 = 480)]
    [XmlElement("IMPUESTOS_--5fEXT")]
    public string Impuestos_Ext
    { 
       get
       {
          return _Impuestos_Ext;
       }
       set
       {
          _Impuestos_Ext = value;
       }
    }
    private string _Impuestos_Ext;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "PAIS_EXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Length2 = 4, Offset = 260, Offset2 = 520)]
    [XmlElement("PAIS_--5fEXT")]
    public string Pais_Ext
    { 
       get
       {
          return _Pais_Ext;
       }
       set
       {
          _Pais_Ext = value;
       }
    }
    private string _Pais_Ext;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "DEPENDIENTES", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Length2 = 4, Offset = 262, Offset2 = 524)]
    [XmlElement("DEPENDIENTES")]
    public string Dependientes
    { 
       get
       {
          return _Dependientes;
       }
       set
       {
          _Dependientes = value;
       }
    }
    private string _Dependientes;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "EDADES_DEP", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 30, Length2 = 60, Offset = 264, Offset2 = 528)]
    [XmlElement("EDADES_--5fDEP")]
    public string Edades_Dep
    { 
       get
       {
          return _Edades_Dep;
       }
       set
       {
          _Edades_Dep = value;
       }
    }
    private string _Edades_Dep;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FECHA_RECEPCION", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 294, Offset2 = 588)]
    [XmlElement("FECHA_--5fRECEPCION")]
    public string Fecha_Recepcion
    { 
       get
       {
          return _Fecha_Recepcion;
       }
       set
       {
          _Fecha_Recepcion = value;
       }
    }
    private string _Fecha_Recepcion;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "FECHA_DEFUNCION", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 302, Offset2 = 604)]
    [XmlElement("FECHA_--5fDEFUNCION")]
    public string Fecha_Defuncion
    { 
       get
       {
          return _Fecha_Defuncion;
       }
       set
       {
          _Fecha_Defuncion = value;
       }
    }
    private string _Fecha_Defuncion;

  }

}
