
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 04/02/2011
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace ZConsultaBuro
{
  /// <summary>
  /// A typed collection of Z00_BURO_RS elements.
  /// </summary>
  [Serializable]
  public class Z00_BURO_RSTable : SAPTable 
  {
  
    /// <summary>
    /// Returns the element type Z00_BURO_RS.
    /// </summary>
    /// <returns>The type Z00_BURO_RS.</returns>
    public override Type GetElementType() 
    {
        return (typeof(Z00_BURO_RS));
    }

    /// <summary>
    /// Creates an empty new row of type Z00_BURO_RS.
    /// </summary>
    /// <returns>The newZ00_BURO_RS.</returns>
    public override object CreateNewRow()
    { 
        return new Z00_BURO_RS();
    }
     
    /// <summary>
    /// The indexer of the collection.
    /// </summary>
    public Z00_BURO_RS this[int index] 
    {
        get 
        {
            return ((Z00_BURO_RS)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    /// <summary>
    /// Adds a Z00_BURO_RS to the end of the collection.
    /// </summary>
    /// <param name="value">The Z00_BURO_RS to be added to the end of the collection.</param>
    /// <returns>The index of the newZ00_BURO_RS.</returns>
    public int Add(Z00_BURO_RS value) 
    {
        return List.Add(value);
    }
        
    /// <summary>
    /// Inserts a Z00_BURO_RS into the collection at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index at which value should be inserted.</param>
    /// <param name="value">The Z00_BURO_RS to insert.</param>
    public void Insert(int index, Z00_BURO_RS value) 
    {
        List.Insert(index, value);
    }
        
    /// <summary>
    /// Searches for the specified Z00_BURO_RS and returnes the zero-based index of the first occurrence in the collection.
    /// </summary>
    /// <param name="value">The Z00_BURO_RS to locate in the collection.</param>
    /// <returns>The index of the object found or -1.</returns>
    public int IndexOf(Z00_BURO_RS value) 
    {
        return List.IndexOf(value);
    }
        
    /// <summary>
    /// Determines wheter an element is in the collection.
    /// </summary>
    /// <param name="value">The Z00_BURO_RS to locate in the collection.</param>
    /// <returns>True if found; else false.</returns>
    public bool Contains(Z00_BURO_RS value) 
    {
        return List.Contains(value);
    }
        
    /// <summary>
    /// Removes the first occurrence of the specified Z00_BURO_RS from the collection.
    /// </summary>
    /// <param name="value">The Z00_BURO_RS to remove from the collection.</param>
    public void Remove(Z00_BURO_RS value) 
    {
        List.Remove(value);
    }

    /// <summary>
    /// Copies the contents of the Z00_BURO_RSTable to the specified one-dimensional array starting at the specified index in the target array.
    /// </summary>
    /// <param name="array">The one-dimensional destination array.</param>           
    /// <param name="index">The zero-based index in array at which copying begins.</param>           
    public void CopyTo(Z00_BURO_RS[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
